# Generated by Django 4.2.6 on 2023-10-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя отправка напоминания'),
        ),
    ]
